force-app/main/default/objects/Opportunity/fields/Competitor_1__c.field-meta.xml
<CustomField>
    <fullName>Competitor_1__c</fullName>
    <label>Competitor 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Competitors</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Competitor_2__c.field-meta.xml
<CustomField>
    <fullName>Competitor_2__c</fullName>
    <label>Competitor 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Competitors</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Competitor_3__c.field-meta.xml
<CustomField>
    <fullName>Competitor_3__c</fullName>
    <label>Competitor 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Competitors</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Leading_Competitor__c.field-meta.xml
<CustomField>
    <fullName>Leading_Competitor__c</fullName>
    <label>Leading Competitor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Competitors</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MostExpensiveCompetitor__c.field-meta.xml
<CustomField>
    <fullName>MostExpensiveCompetitor__c</fullName>
    <label>Most Expensive Competitor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Competitors</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MostExpensiveCompetitorPrice__c.field-meta.xml
<CustomField>
    <fullName>MostExpensiveCompetitorPrice__c</fullName>
    <label>Most Expensive Competitor Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/Competitors.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Amazon</fullName>
    </customValue>
    <customValue>
        <fullName>Google</fullName>
    </customValue>
    <customValue>
        <fullName>Microsoft</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <customValue>
        <fullName>Yahoo!</fullName>
    </customValue>
    <masterLabel>Competitors</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityCompetitorTest.cls
@isTest
public class OpportunityCompetitorTest {
    @isTest static void createOpportunity() {
        // Create Opportunity with required fields
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opportunity';
        opp.AccountId = '0013600001ePOfvAAG';
        opp.StageName = 'Prospecting';
        opp.CloseDate = Date.today();

        // Set Competitor fields
        opp.Competitor_1__c = 'Amazon';
        opp.Competitor_2__c = 'Google';
        opp.Competitor_3__c = 'Salesforce';

        //Set Competitor price fields
        opp.Competitor_1_Price__c = 100;
        opp.Competitor_2_Price__c = 200;
        opp.Competitor_3_Price__c = 300;
        insert opp;
        
        //Verify values on test opp are expected
        opp = [SELECT Id, Leading_Competitor__c, MostExpensiveCompetitor__c,MostExpensiveCompetitorPrice__c FROM Opportunity where Id=:opp.Id];
        System.Assert(opp.Leading_Competitor__c == 'Amazon');
        System.assert(opp.MostExpensiveCompetitor__c == 'Salesforce');
        System.assert(opp.MostExpensiveCompetitorPrice__c == 300);   
    }
}